package com.mapbox.maps.mapbox_maps

import com.mapbox.maps.mapbox_maps.pigeons.*
import android.annotation.SuppressLint
import android.content.Context
import android.content.res.Resources
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleOwner
import com.mapbox.api.directions.v5.utils.ParseUtils
import com.mapbox.bindgen.Expected
import com.mapbox.common.location.Location
import com.mapbox.maps.EdgeInsets
import com.mapbox.maps.MapView
import com.mapbox.maps.plugin.locationcomponent.LocationComponentPlugin
import com.mapbox.maps.plugin.locationcomponent.OnIndicatorPositionChangedListener
import com.mapbox.maps.plugin.locationcomponent.location
import com.mapbox.navigation.base.ExperimentalPreviewMapboxNavigationAPI
import com.mapbox.navigation.base.TimeFormat
import com.mapbox.navigation.base.extensions.applyDefaultNavigationOptions
import com.mapbox.navigation.base.extensions.applyLanguageAndVoiceUnitOptions
import com.mapbox.navigation.base.formatter.DistanceFormatterOptions
import com.mapbox.navigation.base.route.NavigationRoute
import com.mapbox.navigation.base.route.NavigationRouterCallback
import com.mapbox.navigation.base.route.RouteAlternativesOptions
import com.mapbox.navigation.base.route.RouterFailure
import com.mapbox.navigation.base.route.RouterOrigin
import com.mapbox.navigation.core.MapboxNavigation
import com.mapbox.navigation.core.arrival.ArrivalObserver
import com.mapbox.navigation.core.directions.session.RoutesObserver
import com.mapbox.navigation.core.directions.session.RoutesUpdatedResult
import com.mapbox.navigation.core.formatter.MapboxDistanceFormatter
import com.mapbox.navigation.core.lifecycle.MapboxNavigationApp
import com.mapbox.navigation.core.replay.route.ReplayProgressObserver
import com.mapbox.navigation.core.replay.route.ReplayRouteMapper
import com.mapbox.navigation.core.trip.session.BannerInstructionsObserver
import com.mapbox.navigation.core.trip.session.LocationMatcherResult
import com.mapbox.navigation.core.trip.session.LocationObserver
import com.mapbox.navigation.core.trip.session.OffRouteObserver
import com.mapbox.navigation.core.trip.session.RouteProgressObserver
import com.mapbox.navigation.core.trip.session.VoiceInstructionsObserver
import com.mapbox.navigation.tripdata.maneuver.api.MapboxManeuverApi
import com.mapbox.navigation.tripdata.progress.api.MapboxTripProgressApi
import com.mapbox.navigation.tripdata.progress.model.DistanceRemainingFormatter
import com.mapbox.navigation.tripdata.progress.model.EstimatedTimeOfArrivalFormatter
import com.mapbox.navigation.tripdata.progress.model.PercentDistanceTraveledFormatter
import com.mapbox.navigation.tripdata.progress.model.TimeRemainingFormatter
import com.mapbox.navigation.tripdata.progress.model.TripProgressUpdateFormatter
import com.mapbox.navigation.ui.base.util.MapboxNavigationConsumer
import com.mapbox.maps.plugin.animation.camera
import com.mapbox.navigation.ui.maps.camera.NavigationCamera
import com.mapbox.navigation.ui.maps.camera.data.MapboxNavigationViewportDataSource
import com.mapbox.navigation.ui.maps.camera.transition.NavigationCameraTransitionOptions
import com.mapbox.navigation.ui.maps.location.NavigationLocationProvider
import com.mapbox.navigation.ui.maps.route.arrow.api.MapboxRouteArrowApi
import com.mapbox.navigation.ui.maps.route.arrow.api.MapboxRouteArrowView
import com.mapbox.navigation.ui.maps.route.arrow.model.RouteArrowOptions
import com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi
import com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineView
import com.mapbox.navigation.ui.maps.route.line.model.MapboxRouteLineApiOptions
import com.mapbox.navigation.ui.maps.route.line.model.MapboxRouteLineViewOptions
import com.mapbox.navigation.voice.api.MapboxSpeechApi
import com.mapbox.navigation.voice.api.MapboxVoiceInstructionsPlayer
import com.mapbox.navigation.voice.model.SpeechAnnouncement
import com.mapbox.navigation.voice.model.SpeechError
import com.mapbox.navigation.voice.model.SpeechValue
import com.mapbox.navigation.voice.model.SpeechVolume
import io.flutter.Log
import java.util.Locale
import kotlin.time.Duration.Companion.seconds

/**
 * Main navigation controller that bridges Flutter and Mapbox Navigation SDK.
 * 
 * This class implements the NavigationInterface generated by Pigeon and manages
 * all navigation-related functionality including route management, progress tracking,
 * voice instructions, camera control, and event broadcasting.
 */
@SuppressLint("VisibleForTests")
@OptIn(ExperimentalPreviewMapboxNavigationAPI::class)
class NavigationController(
  private val context: Context,
  private val mapView: MapView,
  override val lifecycle: Lifecycle,
  private val eventListener: NavigationEventListener
) : NavigationInterface, LifecycleOwner {

  // ============================================================================
  // STATE MANAGEMENT
  // ============================================================================

  private var currentState: NavigationState = NavigationState.IDLE
    set(value) {
      if (field != value) {
        field = value
        broadcastNavigationState(value)
      }
    }

  private var currentCameraMode: CameraMode = CameraMode.IDLE
  private var currentProgress: com.mapbox.navigation.base.trip.model.RouteProgress? = null
  private var currentLocation: LocationMatcherResult? = null
  private var currentRoutes: List<NavigationRoute> = emptyList()

  // ============================================================================
  // LOCATION & POSITIONING
  // ============================================================================

  private lateinit var locationComponent: LocationComponentPlugin
  private val navigationLocationProvider = NavigationLocationProvider()

  // ============================================================================
  // VISUALIZATION
  // ============================================================================

  private lateinit var maneuverApi: MapboxManeuverApi
  private lateinit var tripProgressApi: MapboxTripProgressApi
  private lateinit var routeLineApi: MapboxRouteLineApi
  private lateinit var routeLineView: MapboxRouteLineView
  private val routeArrowApi: MapboxRouteArrowApi = MapboxRouteArrowApi()
  private lateinit var routeArrowView: MapboxRouteArrowView

  // ============================================================================
  // CAMERA
  // ============================================================================

  private lateinit var navigationCamera: NavigationCamera
  private lateinit var viewportDataSource: MapboxNavigationViewportDataSource
  private val pixelDensity = Resources.getSystem().displayMetrics.density

  private val defaultOverviewPadding: EdgeInsets by lazy {
    EdgeInsets(140.0 * pixelDensity, 40.0 * pixelDensity, 120.0 * pixelDensity, 40.0 * pixelDensity)
  }

  private val defaultFollowingPadding: EdgeInsets by lazy {
    EdgeInsets(180.0 * pixelDensity, 40.0 * pixelDensity, 150.0 * pixelDensity, 40.0 * pixelDensity)
  }

  // ============================================================================
  // VOICE & AUDIO
  // ============================================================================

  private var isVoiceInstructionsMuted = false
  private lateinit var speechApi: MapboxSpeechApi
  private lateinit var voiceInstructionsPlayer: MapboxVoiceInstructionsPlayer
  private var currentVoiceLanguage: String = Locale.getDefault().language
  private var currentVoiceUnits: VoiceUnits = VoiceUnits.METRIC

  // ============================================================================
  // NAVIGATION SDK
  // ============================================================================

  private lateinit var mapboxNavigation: MapboxNavigation
  private lateinit var replayProgressObserver: ReplayProgressObserver
  private val replayRouteMapper = ReplayRouteMapper()

  // ============================================================================
  // VISUAL CUSTOMIZATION (Sprint 2)
  // ============================================================================

  private var routeLineOptions: RouteLineOptions = RouteLineOptions()
  private var maneuverArrowOptions: ManeuverArrowOptions = ManeuverArrowOptions()

  // ============================================================================
  // OBSERVERS
  // ============================================================================

  private var isProgressObserverRegistered = false
  private var isBannerObserverRegistered = false
  private var isVoiceObserverRegistered = false
  private var isRerouteObserverRegistered = false
  private var isArrivalObserverRegistered = false
  private var isOffRouteObserverRegistered = false

  // Location Observer
  private val locationObserver = object : LocationObserver {
    var firstLocationUpdateReceived = false

    override fun onNewRawLocation(rawLocation: Location) {
      // Raw location not used currently
    }

    override fun onNewLocationMatcherResult(locationMatcherResult: LocationMatcherResult) {
      currentLocation = locationMatcherResult
      val enhancedLocation = locationMatcherResult.enhancedLocation

      // Update location puck's position on the map
      navigationLocationProvider.changePosition(
        location = enhancedLocation,
        keyPoints = locationMatcherResult.keyPoints,
      )

      // Update camera position to account for new location
      viewportDataSource.onLocationChanged(enhancedLocation)
      viewportDataSource.evaluate()

      // Initial camera transition
      if (!firstLocationUpdateReceived) {
        firstLocationUpdateReceived = true
        if (currentCameraMode == CameraMode.OVERVIEW) {
          navigationCamera.requestNavigationCameraToOverview(
            stateTransitionOptions = NavigationCameraTransitionOptions.Builder()
              .maxDuration(0)
              .build()
          )
        }
      }
    }
  }

  // Route Progress Observer
  private val routeProgressObserver = RouteProgressObserver { routeProgress ->
    currentProgress = routeProgress

    // Update camera
    viewportDataSource.onRouteProgressChanged(routeProgress)
    viewportDataSource.evaluate()

    // Update maneuver arrow
    val style = mapView.mapboxMap.style
    if (style != null) {
      val maneuverArrowResult = routeArrowApi.addUpcomingManeuverArrow(routeProgress)
      routeArrowView.renderManeuverUpdate(style, maneuverArrowResult)
    }

    // Broadcast to Flutter if observer is registered
    if (isProgressObserverRegistered) {
      broadcastRouteProgress(routeProgress)
    }
  }

  // Routes Observer
  private val routesObserver = RoutesObserver { routeUpdateResult ->
    currentRoutes = routeUpdateResult.navigationRoutes

    if (routeUpdateResult.navigationRoutes.isNotEmpty()) {
      // Generate route geometries asynchronously and render them
      routeLineApi.setNavigationRoutes(routeUpdateResult.navigationRoutes) { value ->
        mapView.mapboxMap.style?.apply {
          routeLineView.renderRouteDrawData(this, value)
        }
      }

      // Update the camera position to account for the new route
      viewportDataSource.onRouteChanged(routeUpdateResult.navigationRoutes.first())
      viewportDataSource.evaluate()
    } else {
      // Remove the route line and route arrow from the map
      val style = mapView.mapboxMap.style
      if (style != null) {
        routeLineApi.clearRouteLine { value ->
          routeLineView.renderClearRouteLineValue(style, value)
        }
        routeArrowView.render(style, routeArrowApi.clearArrows())
      }

      // Remove the route reference from camera position evaluations
      viewportDataSource.clearRouteData()
      viewportDataSource.evaluate()
    }
  }

  // Banner Instructions Observer
  private val bannerInstructionsObserver = BannerInstructionsObserver { bannerInstructions ->
    if (isBannerObserverRegistered) {
      broadcastBannerInstruction(bannerInstructions)
    }
  }

  // Voice Instructions Observer
  private val voiceInstructionsObserver = VoiceInstructionsObserver { voiceInstructions ->
    if (isVoiceObserverRegistered) {
      broadcastVoiceInstruction(voiceInstructions)
    }

    // Speak the instruction
    speechApi.generate(voiceInstructions, speechCallback)
  }

  // Off-Route Observer  
  private val offRouteObserver = OffRouteObserver {
    if (isOffRouteObserverRegistered) {
      broadcastOffRoute()
    }
  }

  // Arrival Observer
  private val arrivalObserver = object : ArrivalObserver {
    override fun onWaypointArrival(routeProgress: com.mapbox.navigation.base.trip.model.RouteProgress) {
      if (isArrivalObserverRegistered) {
        val event = ArrivalEvent(
          finalDestination = false,
          waypointIndex = routeProgress.currentLegProgress?.legIndex?.toLong()
        )
        eventListener.onArrival(event) {}
      }
    }

    override fun onNextRouteLegStart(routeLegProgress: com.mapbox.navigation.base.trip.model.RouteLegProgress) {
      // Called when starting the next leg
    }

    override fun onFinalDestinationArrival(routeProgress: com.mapbox.navigation.base.trip.model.RouteProgress) {
      if (isArrivalObserverRegistered) {
        val event = ArrivalEvent(
          finalDestination = true,
          waypointIndex = routeProgress.currentLegProgress?.legIndex?.toLong()
        )
        eventListener.onArrival(event) {}
      }
    }
  }

  // Speech Callback
  private val speechCallback = MapboxNavigationConsumer<Expected<SpeechError, SpeechValue>> { expected ->
    expected.fold(
      { error ->
        // Play the instruction via fallback text-to-speech engine
        voiceInstructionsPlayer.play(error.fallback, voiceInstructionsPlayerCallback)
      },
      { value ->
        // Play the sound file from the external generator
        voiceInstructionsPlayer.play(value.announcement, voiceInstructionsPlayerCallback)
      }
    )
  }

  // Voice Player Callback
  private val voiceInstructionsPlayerCallback = MapboxNavigationConsumer<SpeechAnnouncement> { value ->
    // Remove already consumed file to free-up space
    speechApi.clean(value)
  }

  // Route line vanishing listener
  private val onPositionChangedListener = OnIndicatorPositionChangedListener { point ->
    val result = routeLineApi.updateTraveledRouteLine(point)
    mapView.mapboxMap.style?.apply {
      routeLineView.renderRouteLineUpdate(this, result)
    }
  }

  // ============================================================================
  // INITIALIZATION
  // ============================================================================

  init {
    initializeComponents()
  }

  private fun initializeComponents() {
    val mapboxMap = mapView.mapboxMap
    val camera = mapView.camera

    // Initialize viewport and camera
    viewportDataSource = MapboxNavigationViewportDataSource(mapboxMap)
    navigationCamera = NavigationCamera(mapboxMap, camera, viewportDataSource)

    // Initialize formatters
    val distanceFormatterOptions = DistanceFormatterOptions.Builder(context).build()
    maneuverApi = MapboxManeuverApi(MapboxDistanceFormatter(distanceFormatterOptions))

    tripProgressApi = MapboxTripProgressApi(
      TripProgressUpdateFormatter.Builder(context)
        .distanceRemainingFormatter(DistanceRemainingFormatter(distanceFormatterOptions))
        .timeRemainingFormatter(TimeRemainingFormatter(context))
        .percentRouteTraveledFormatter(PercentDistanceTraveledFormatter())
        .estimatedTimeOfArrivalFormatter(EstimatedTimeOfArrivalFormatter(context, TimeFormat.TWENTY_FOUR_HOURS))
        .build()
    )

    // Initialize speech
    speechApi = MapboxSpeechApi(context, currentVoiceLanguage)
    voiceInstructionsPlayer = MapboxVoiceInstructionsPlayer(context, currentVoiceLanguage)

    // Initialize route line
    val mapboxRouteLineViewOptions = MapboxRouteLineViewOptions.Builder(context)
      .routeLineBelowLayerId("road-label-navigation")
      .build()

   routeLineApi = MapboxRouteLineApi(MapboxRouteLineApiOptions.Builder().build())
    routeLineView = MapboxRouteLineView(mapboxRouteLineViewOptions)

    // Initialize maneuver arrow
    val routeArrowOptions = RouteArrowOptions.Builder(context).build()
    routeArrowView = MapboxRouteArrowView(routeArrowOptions)

    // Initialize MapboxNavigation
    MapboxNavigationApp.setup(
      com.mapbox.navigation.base.options.NavigationOptions.Builder(context)
        .routeAlternativesOptions(
          RouteAlternativesOptions.Builder()
            .intervalMillis(30.seconds.inWholeMilliseconds)
            .build()
        )
        .build()
    )

    MapboxNavigationApp.attach(this)
    mapboxNavigation = MapboxNavigationApp.current()!!

    // Register core observers
    mapboxNavigation.registerRoutesObserver(routesObserver)
    mapboxNavigation.registerLocationObserver(locationObserver)

    // Initialize replay for testing
    replayProgressObserver = ReplayProgressObserver(mapboxNavigation.mapboxReplayer)
  }

  // ============================================================================
  // NAVIGATION INTERFACE IMPLEMENTATION - SESSION MANAGEMENT
  // ============================================================================

  override fun startNavigation(options: NavigationOptions, callback: (Result<Boolean>) -> Unit) {
    try {
      Log.d(LOG_TAG, "Starting navigation with options: $options")

      // Set up location component
      locationComponent = mapView.location.apply {
        setLocationProvider(navigationLocationProvider)
        addOnIndicatorPositionChangedListener(onPositionChangedListener)
        enabled = true
      }

      // Configure viewport
      viewportDataSource.options.followingFrameOptions.defaultPitch = 35.0
      viewportDataSource.evaluate()

      // Apply camera mode
      val initialMode = options.initialCameraMode ?: CameraMode.FOLLOWING
      setCameraMode(initialMode)

      // Start trip session
      mapboxNavigation.startTripSession()

      currentState = if (currentRoutes.isEmpty()) {
        NavigationState.FREE_DRIVE
      } else {
        NavigationState.ACTIVE_GUIDANCE
      }

      callback(Result.success(true))
    } catch (e: Exception) {
      Log.e(LOG_TAG, "Failed to start navigation", e)
      callback(Result.failure(e))
    }
  }

  override fun stopNavigation(callback: (Result<Boolean>) -> Unit) {
    try {
      Log.d(LOG_TAG, "Stopping navigation")

      // Stop trip session
      mapboxNavigation.stopTripSession()

      // Clear routes
      mapboxNavigation.setNavigationRoutes(emptyList())

      // Remove location listener
      if (::locationComponent.isInitialized) {
        locationComponent.removeOnIndicatorPositionChangedListener(onPositionChangedListener)
      }

      currentState = NavigationState.STOPPED
      currentProgress = null
      currentLocation = null

      callback(Result.success(true))
    } catch (e: Exception) {
      Log.e(LOG_TAG, "Failed to stop navigation", e)
      callback(Result.failure(e))
    }
  }

  override fun pauseNavigation(callback: (Result<Boolean>) -> Unit) {
    try {
      // Mapbox Navigation doesn't have explicit pause, but we can stop guidance
      // while keeping the session alive
      mapboxNavigation.stopTripSession()
      currentState = NavigationState.IDLE
      callback(Result.success(true))
    } catch (e: Exception) {
      callback(Result.failure(e))
    }
  }

  override fun resumeNavigation(callback: (Result<Boolean>) -> Unit) {
    try {
      mapboxNavigation.startTripSession()
      currentState = if (currentRoutes.isEmpty()) {
        NavigationState.FREE_DRIVE
      } else {
        NavigationState.ACTIVE_GUIDANCE
      }
      callback(Result.success(true))
    } catch (e: Exception) {
      callback(Result.failure(e))
    }
  }

  override fun getNavigationState(): NavigationState {
    return currentState
  }

  // ============================================================================
  // NAVIGATION INTERFACE IMPLEMENTATION - ROUTE MANAGEMENT
  // ============================================================================

  override fun setRoute(options: RouteOptions, callback: (Result<Boolean>) -> Unit) {
    try {
      Log.d(LOG_TAG, "Setting route with options")

      val coordinates = ParseUtils.parseToPoints(options.coordinates) ?: run {
        callback(Result.failure(IllegalArgumentException("Invalid coordinates")))
        return
      }

      // Build route options
      val routeOptionsBuilder = com.mapbox.api.directions.v5.models.RouteOptions.builder()
        .applyDefaultNavigationOptions()
        .coordinatesList(coordinates)

      // Apply profile
      val profile = options.profile ?: "mapbox/driving-traffic"
      routeOptionsBuilder.profile(profile)

      // Apply optional parameters
      options.alternatives?.let { routeOptionsBuilder.alternatives(it) }
      options.language?.let { routeOptionsBuilder.language(it) }
      options.voiceInstructions?.let { routeOptionsBuilder.voiceInstructions(it) }
      options.bannerInstructions?.let { routeOptionsBuilder.bannerInstructions(it) }
      options.steps?.let { routeOptionsBuilder.steps(it) }
      options.continueStraight?.let { routeOptionsBuilder.continueStraight(it) }
      options.waypointNames?.let { routeOptionsBuilder.waypointNamesList(it.split(";")) }
      options.exclude?.let { routeOptionsBuilder.exclude(it) }
      // Walking options not currently supported in this SDK version
      options.maxHeight?.let { routeOptionsBuilder.maxHeight(it) }
      options.maxWidth?.let { routeOptionsBuilder.maxWidth(it) }
      options.maxWeight?.let { routeOptionsBuilder.maxWeight(it) }

      // Add layers for proper map matching
      routeOptionsBuilder.layersList(listOf(mapboxNavigation.getZLevel(), null))

      val finalRouteOptions = routeOptionsBuilder.build()

      // Request routes
      mapboxNavigation.requestRoutes(
        finalRouteOptions,
        object : NavigationRouterCallback {
          override fun onRoutesReady(
            routes: List<NavigationRoute>,
            @RouterOrigin routerOrigin: String
          ) {
            Log.d(LOG_TAG, "Routes ready: ${routes.size} route(s)")

            if (routes.isNotEmpty()) {
              // Set the routes for navigation
              mapboxNavigation.setNavigationRoutes(routes)

              // Update state
              if (currentState == NavigationState.ACTIVE_GUIDANCE || currentState == NavigationState.FREE_DRIVE) {
                currentState = NavigationState.ACTIVE_GUIDANCE
              }
            }

            callback(Result.success(true))
          }

          override fun onFailure(
            reasons: List<RouterFailure>,
            routeOptions: com.mapbox.api.directions.v5.models.RouteOptions
          ) {
            Log.e(LOG_TAG, "Route request failed: $reasons")
            callback(Result.failure(Exception(reasons.toString())))
          }

          override fun onCanceled(
            routeOptions: com.mapbox.api.directions.v5.models.RouteOptions,
            @RouterOrigin routerOrigin: String
          ) {
            Log.d(LOG_TAG, "Route request canceled")
            callback(Result.failure(Exception("Route request canceled")))
          }
        }
      )
    } catch (e: Exception) {
      Log.e(LOG_TAG, "Failed to set route", e)
      callback(Result.failure(e))
    }
  }

  override fun clearRoute(callback: (Result<Boolean>) -> Unit) {
    try {
      mapboxNavigation.setNavigationRoutes(emptyList())
      currentProgress = null
      
      if (currentState == NavigationState.ACTIVE_GUIDANCE) {
        currentState = NavigationState.FREE_DRIVE
      }
      
      callback(Result.success(true))
    } catch (e: Exception) {
      callback(Result.failure(e))
    }
  }

  override fun getRouteAlternatives(callback: (Result<List<RouteAlternative>>) -> Unit) {
    try {
      val alternatives = currentRoutes.drop(1).mapIndexed { index, route ->
        val directionsRoute = route.directionsRoute
        RouteAlternative(
          id = "alt_$index",
          distance = directionsRoute.distance(),
          duration = directionsRoute.duration(),
          distanceDelta = null, // Would need to calculate vs primary
          durationDelta = null
        )
      }
      callback(Result.success(alternatives))
    } catch (e: Exception) {
      callback(Result.failure(e))
    }
  }

  override fun selectAlternativeRoute(routeId: String, callback: (Result<Boolean>) -> Unit) {
    try {
      // Parse the alternative index from the ID
      val index = routeId.removePrefix("alt_").toIntOrNull()?.plus(1) ?: run {
        callback(Result.failure(IllegalArgumentException("Invalid route ID")))
        return
      }

      if (index < currentRoutes.size) {
        // Reorder routes to make the selected one primary
        val selectedRoute = currentRoutes[index]
        val newRoutes = listOf(selectedRoute) + currentRoutes.filterIndexed { i, _ -> i != index }
        mapboxNavigation.setNavigationRoutes(newRoutes)
        callback(Result.success(true))
      } else {
        callback(Result.failure(IllegalArgumentException("Route not found")))
      }
    } catch (e: Exception) {
      callback(Result.failure(e))
    }
  }

  // ============================================================================
  // NAVIGATION INTERFACE IMPLEMENTATION - PROGRESS & STATE QUERIES
  // ============================================================================

  override fun getCurrentProgress(): RouteProgress? {
    return currentProgress?.let { convertRouteProgress(it) }
  }

  override fun getCurrentLocation(): EnhancedLocation? {
    return currentLocation?.let { convertEnhancedLocation(it) }
  }

  // ============================================================================
  // NAVIGATION INTERFACE IMPLEMENTATION - CAMERA CONTROL
  // ============================================================================

  override fun setCameraMode(mode: CameraMode) {
    currentCameraMode = mode
    when (mode) {
      CameraMode.IDLE -> {
        // Camera doesn't follow
      }
      CameraMode.OVERVIEW -> {
        navigationCamera.requestNavigationCameraToOverview()
      }
      CameraMode.FOLLOWING -> {
        navigationCamera.requestNavigationCameraToFollowing()
      }
    }
  }

  override fun getCameraMode(): CameraMode {
    return currentCameraMode
  }

  override fun setCameraPadding(padding: CameraPadding) {
    val edgeInsets = EdgeInsets(
      padding.top * pixelDensity,
      padding.left * pixelDensity,
      padding.bottom * pixelDensity,
      padding.right * pixelDensity
    )

    viewportDataSource.overviewPadding = edgeInsets
    viewportDataSource.followingPadding = edgeInsets
    viewportDataSource.evaluate()
  }

  // ============================================================================
  // NAVIGATION INTERFACE IMPLEMENTATION - VOICE & INSTRUCTIONS
  // ============================================================================

  override fun setVoiceMuted(muted: Boolean) {
    isVoiceInstructionsMuted = muted
    if (muted) {
      voiceInstructionsPlayer.volume(SpeechVolume(0f))
    } else {
      voiceInstructionsPlayer.volume(SpeechVolume(1f))
    }
  }

  override fun isVoiceMuted(): Boolean {
    return isVoiceInstructionsMuted
  }

  override fun setVoiceLanguage(languageCode: String) {
    if (currentVoiceLanguage != languageCode) {
      currentVoiceLanguage = languageCode
      
      // Recreate speech API and player with new language
      speechApi.cancel()
      voiceInstructionsPlayer.shutdown()
      
      speechApi = MapboxSpeechApi(context, languageCode)
      voiceInstructionsPlayer = MapboxVoiceInstructionsPlayer(context, languageCode)
      
      if (isVoiceInstructionsMuted) {
        voiceInstructionsPlayer.volume(SpeechVolume(0f))
      }
    }
  }

  override fun setVoiceUnits(units: VoiceUnits) {
    currentVoiceUnits = units
    // Voice units are applied during route request
  }

  // ============================================================================
  // NAVIGATION INTERFACE IMPLEMENTATION - EVENT REGISTRATION
  // ============================================================================

  override fun registerProgressObserver() {
    if (!isProgressObserverRegistered) {
      mapboxNavigation.registerRouteProgressObserver(routeProgressObserver)
      mapboxNavigation.registerRouteProgressObserver(replayProgressObserver)
      isProgressObserverRegistered = true
    }
  }

  override fun unregisterProgressObserver() {
    if (isProgressObserverRegistered) {
      mapboxNavigation.unregisterRouteProgressObserver(routeProgressObserver)
      mapboxNavigation.unregisterRouteProgressObserver(replayProgressObserver)
      isProgressObserverRegistered = false
    }
  }

  override fun registerBannerObserver() {
    if (!isBannerObserverRegistered) {
      mapboxNavigation.registerBannerInstructionsObserver(bannerInstructionsObserver)
      isBannerObserverRegistered = true
    }
  }

  override fun unregisterBannerObserver() {
    if (isBannerObserverRegistered) {
      mapboxNavigation.unregisterBannerInstructionsObserver(bannerInstructionsObserver)
      isBannerObserverRegistered = false
    }
  }

  override fun registerVoiceObserver() {
    if (!isVoiceObserverRegistered) {
      mapboxNavigation.registerVoiceInstructionsObserver(voiceInstructionsObserver)
      isVoiceObserverRegistered = true
    }
  }

  override fun unregisterVoiceObserver() {
    if (isVoiceObserverRegistered) {
      mapboxNavigation.unregisterVoiceInstructionsObserver(voiceInstructionsObserver)
      isVoiceObserverRegistered = false
    }
  }

  override fun registerRerouteObserver() {
    // Reroute detection is automatic in Mapbox Navigation SDK
    // Events will be broadcast through routes observer
    isRerouteObserverRegistered = true
  }

  override fun unregisterRerouteObserver() {
    isRerouteObserverRegistered = false
  }

  override fun registerArrivalObserver() {
    if (!isArrivalObserverRegistered) {
      mapboxNavigation.registerArrivalObserver(arrivalObserver)
      isArrivalObserverRegistered = true
    }
  }

  override fun unregisterArrivalObserver() {
    if (isArrivalObserverRegistered) {
      mapboxNavigation.unregisterArrivalObserver(arrivalObserver)
      isArrivalObserverRegistered = false
    }
  }

  override fun registerOffRouteObserver() {
    if (!isOffRouteObserverRegistered) {
      mapboxNavigation.registerOffRouteObserver(offRouteObserver)
      isOffRouteObserverRegistered = true
    }
  }

  override fun unregisterOffRouteObserver() {
    if (isOffRouteObserverRegistered) {
      mapboxNavigation.unregisterOffRouteObserver(offRouteObserver)
      isOffRouteObserverRegistered = false
    }
  }

  // ============================================================================
  // LIFECYCLE & CLEANUP
  // ============================================================================

  fun dispose() {
    // Unregister all observers
    unregisterProgressObserver()
    unregisterBannerObserver()
    unregisterVoiceObserver()
    unregisterArrivalObserver()
    unregisterOffRouteObserver()

    mapboxNavigation.unregisterRoutesObserver(routesObserver)
    mapboxNavigation.unregisterLocationObserver(locationObserver)

    // Clean up APIs
    maneuverApi.cancel()
    routeLineApi.cancel()
    routeLineView.cancel()
    speechApi.cancel()
    voiceInstructionsPlayer.shutdown()

    if (::locationComponent.isInitialized) {
      locationComponent.removeOnIndicatorPositionChangedListener(onPositionChangedListener)
    }

    mapboxNavigation.mapboxReplayer.finish()
  }

  // ============================================================================
  // HELPER METHODS - TYPE CONVERSIONS
  // ============================================================================

  private fun convertRouteProgress(progress: com.mapbox.navigation.base.trip.model.RouteProgress): RouteProgress {
    val currentLegProgress = progress.currentLegProgress
    val currentStepProgress = currentLegProgress?.currentStepProgress

    return RouteProgress(
      distanceRemaining = progress.distanceRemaining.toDouble(),
      durationRemaining = progress.durationRemaining,
      distanceTraveled = progress.distanceTraveled.toDouble(),
      fractionTraveled = progress.fractionTraveled.toDouble(),
      currentStepIndex = currentStepProgress?.stepIndex?.toLong(),
      currentLegIndex = progress.currentLegProgress?.legIndex?.toLong(),
      upcomingStepIndex = currentStepProgress?.stepIndex?.plus(1)?.toLong(),
      currentStep = currentStepProgress?.step?.let { convertRouteStep(it, currentStepProgress) },
      upcomingStep = null, // Would need to get from route
      currentRoadName = currentStepProgress?.step?.name(),
      currentSpeedLimit = null, // Speed limit requires SpeedLimitObserver registration
      congestionLevel = null // Would need congestion data from route
    )
  }

  private fun convertRouteStep(
    step: com.mapbox.api.directions.v5.models.LegStep,
    stepProgress: com.mapbox.navigation.base.trip.model.RouteStepProgress
  ): RouteStep {
    // Extract lane info from first intersection
    val laneInfo = step.intersections()?.firstOrNull()?.lanes()?.let { convertLaneInfo(it) }

    return RouteStep(
      distance = step.distance(),
      duration = step.duration(),
      name = step.name(),
      instruction = step.maneuver().instruction(),
      maneuverType = convertManeuverType(step.maneuver().type()),
      maneuverModifier = convertManeuverModifier(step.maneuver().modifier()),
      distanceToManeuver = stepProgress.distanceRemaining.toDouble(),
      estimatedTimeToManeuver = stepProgress.durationRemaining,
      exitNumbers = step.exits(),
      laneInfo = laneInfo
    )
  }

  private fun convertManeuverType(type: String?): ManeuverType? {
    return when (type) {
      "turn" -> ManeuverType.TURN
      "new name" -> ManeuverType.NEW_NAME
      "depart" -> ManeuverType.DEPART
      "arrive" -> ManeuverType.ARRIVE
      "merge" -> ManeuverType.MERGE
      "on ramp" -> ManeuverType.ON_RAMP
      "off ramp" -> ManeuverType.OFF_RAMP
      "fork" -> ManeuverType.FORK
      "end of road" -> ManeuverType.END_OF_ROAD
      "continue" -> ManeuverType.CONTINUE_
      "roundabout" -> ManeuverType.ROUNDABOUT
      "rotary" -> ManeuverType.ROTARY
      "roundabout turn" -> ManeuverType.ROUNDABOUT_TURN
      "notification" -> ManeuverType.NOTIFICATION
      "exit roundabout" -> ManeuverType.EXIT_ROUNDABOUT
      "exit rotary" -> ManeuverType.EXIT_ROTARY
      else -> null
    }
  }

  private fun convertManeuverModifier(modifier: String?): ManeuverModifier? {
    return when (modifier) {
      "uturn" -> ManeuverModifier.UTURN
      "sharp right" -> ManeuverModifier.SHARP_RIGHT
      "right" -> ManeuverModifier.RIGHT
      "slight right" -> ManeuverModifier.SLIGHT_RIGHT
      "straight" -> ManeuverModifier.STRAIGHT
      "slight left" -> ManeuverModifier.SLIGHT_LEFT
      "left" -> ManeuverModifier.LEFT
      "sharp left" -> ManeuverModifier.SHARP_LEFT
      else -> null
    }
  }

  private fun convertEnhancedLocation(result: LocationMatcherResult): EnhancedLocation {
    val location = result.enhancedLocation
    return EnhancedLocation(
      latitude = location.latitude,
      longitude = location.longitude,
      bearing = location.bearing?.toDouble(),
      speed = location.speed?.toDouble(),
      altitude = location.altitude,
      accuracy = location.horizontalAccuracy?.toDouble(),
      timestamp = location.timestamp?.toLong(),
      isMatched = result.isTeleport.not(),
      roadName = null // Would need to get from current step
    )
  }

  // ============================================================================
  // HELPER METHODS - EVENT BROADCASTING
  // ============================================================================

  private fun broadcastRouteProgress(progress: com.mapbox.navigation.base.trip.model.RouteProgress) {
    val event = RouteProgressEvent(
      progress = convertRouteProgress(progress),
      timestamp = System.currentTimeMillis()
    )
    eventListener.onRouteProgress(event) {}
  }

  private fun broadcastBannerInstruction(instruction: com.mapbox.api.directions.v5.models.BannerInstructions) {
    val primary = instruction.primary()
    val bannerInstruction = BannerInstruction(
      primaryText = primary.text(),
      secondaryText = instruction.secondary()?.text(),
      distanceToManeuver = instruction.distanceAlongGeometry(),
      maneuverType = convertManeuverType(primary.type()),
      maneuverModifier = convertManeuverModifier(primary.modifier()),
      drivingSide = primary.drivingSide(),
      degrees = primary.degrees()?.toDouble()
    )
    eventListener.onBannerInstruction(bannerInstruction) {}
  }

  private fun broadcastVoiceInstruction(instruction: com.mapbox.api.directions.v5.models.VoiceInstructions) {
    val announcementText = instruction.announcement() ?: return
    val voiceInstruction = VoiceInstruction(
      announcement = announcementText,
      ssmlAnnouncement = instruction.ssmlAnnouncement() ?: announcementText,
      distanceAlongGeometry = instruction.distanceAlongGeometry()
    )
    eventListener.onVoiceInstruction(voiceInstruction) {}
  }

  private fun broadcastOffRoute() {
    val currentLoc = currentLocation?.enhancedLocation
    val event = OffRouteEvent(
      distanceFromRoute = 0.0, // Would need to calculate actual distance
      timestamp = System.currentTimeMillis()
    )
    eventListener.onOffRoute(event) {}
  }

  private fun broadcastNavigationState(state: NavigationState) {
    val event = NavigationStateEvent(
      state = state,
      timestamp = System.currentTimeMillis()
    )
    eventListener.onNavigationStateChanged(event) {}
  }

  // ============================================================================
  // SPRINT 2 IMPLEMENTATION - VISUAL CUSTOMIZATION
  // ============================================================================

  override fun setRouteLineOptions(options: RouteLineOptions) {
    routeLineOptions = options
    updateRouteLineStyle()
  }

  override fun getRouteLineOptions(): RouteLineOptions {
    return routeLineOptions
  }

  override fun setManeuverArrowOptions(options: ManeuverArrowOptions) {
    maneuverArrowOptions = options
    updateManeuverArrowStyle()
  }

  override fun getManeuverArrowOptions(): ManeuverArrowOptions {
    return maneuverArrowOptions
  }

  override fun setCameraModeAnimated(mode: CameraMode, options: CameraAnimationOptions) {
    val transitionOptions = NavigationCameraTransitionOptions.Builder()
      .apply {
        options.maxDuration?.let { maxDuration(it.toLong()) }
        options.duration?.let { maxDuration(it.toLong()) }
      }
      .build()

    currentCameraMode = mode
    when (mode) {
      CameraMode.IDLE -> {
        // Camera doesn't follow
      }
      CameraMode.OVERVIEW -> {
        navigationCamera.requestNavigationCameraToOverview(
          stateTransitionOptions = transitionOptions
        )
      }
      CameraMode.FOLLOWING -> {
        navigationCamera.requestNavigationCameraToFollowing(
          stateTransitionOptions = transitionOptions
        )
      }
    }
  }

  private fun updateRouteLineStyle() {
    try {
      // Build API options
      val apiOptions = MapboxRouteLineApiOptions.Builder()
        .apply {
          routeLineOptions.enableVanishingRouteLine?.let {
            vanishingRouteLineEnabled(it)
          }
        }
        .build()

      // Build view options with colors
      val viewOptions = MapboxRouteLineViewOptions.Builder(context)
        .apply {
          routeLineOptions.primaryRouteColor?.let { color ->
            // Note: Mapbox expects colors, we'll apply via resource builder
            displayRestrictedRoadSections(true)
          }
          
          routeLineBelowLayerId("road-label-navigation")
        }
        .build()

      // Recreate route line API and view
      routeLineApi = MapboxRouteLineApi(apiOptions)
      routeLineView = MapboxRouteLineView(viewOptions)

      // Re-render current routes if any
      if (currentRoutes.isNotEmpty()) {
        routeLineApi.setNavigationRoutes(currentRoutes) { value ->
          mapView.mapboxMap.style?.apply {
            routeLineView.renderRouteDrawData(this, value)
          }
        }
      }

      Log.d(LOG_TAG, "Route line style updated")
    } catch (e: Exception) {
      Log.e(LOG_TAG, "Failed to update route line style", e)
    }
  }

  private fun updateManeuverArrowStyle() {
    try {
      val arrowOptions = RouteArrowOptions.Builder(context)
        .apply {
          maneuverArrowOptions.arrowColor?.let { 
            // withArrowColor(it) // Method availability depends on SDK version
          }
          maneuverArrowOptions.arrowBorderColor?.let {
            // withArrowBorderColor(it)
          }
        }
        .build()

      routeArrowView = MapboxRouteArrowView(arrowOptions)

      Log.d(LOG_TAG, "Maneuver arrow style updated")
    } catch (e: Exception) {
      Log.e(LOG_TAG, "Failed to update maneuver arrow style", e)
    }
  }

  private fun convertLaneInfo(intersectionLanes: List<com.mapbox.api.directions.v5.models.IntersectionLanes>?): LaneInfo? {
    if (intersectionLanes == null || intersectionLanes.isEmpty()) {
      return null
    }

    val lanes = intersectionLanes.map { lane ->
      Lane(
        valid = lane.valid() ?: false,
        active = lane.active() ?: false,
        directions = lane.indications() ?: emptyList()
      )
    }

    val activeDirection = intersectionLanes
      .firstOrNull { it.active() == true }
      ?.indications()
      ?.firstOrNull()

    return LaneInfo(
      lanes = lanes,
      activeDirection = activeDirection
    )
  }

  companion object {
    private const val LOG_TAG = "NavigationController"
  }
}
