// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mapbox.maps.mapbox_maps.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NavigationInterfacesPigeonUtils {

  fun createConnectionError(channelName: String): NavigationFlutterError {
    return NavigationFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is NavigationFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class NavigationFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class NavigationState(val raw: Int) {
  IDLE(0),
  FREE_DRIVE(1),
  ACTIVE_GUIDANCE(2),
  ARRIVED(3),
  STOPPED(4);

  companion object {
    fun ofRaw(raw: Int): NavigationState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CameraMode(val raw: Int) {
  IDLE(0),
  OVERVIEW(1),
  FOLLOWING(2);

  companion object {
    fun ofRaw(raw: Int): CameraMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VoiceUnits(val raw: Int) {
  IMPERIAL(0),
  METRIC(1);

  companion object {
    fun ofRaw(raw: Int): VoiceUnits? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ManeuverType(val raw: Int) {
  TURN(0),
  NEW_NAME(1),
  DEPART(2),
  ARRIVE(3),
  MERGE(4),
  ON_RAMP(5),
  OFF_RAMP(6),
  FORK(7),
  END_OF_ROAD(8),
  CONTINUE_(9),
  ROUNDABOUT(10),
  ROTARY(11),
  ROUNDABOUT_TURN(12),
  NOTIFICATION(13),
  EXIT_ROUNDABOUT(14),
  EXIT_ROTARY(15);

  companion object {
    fun ofRaw(raw: Int): ManeuverType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ManeuverModifier(val raw: Int) {
  UTURN(0),
  SHARP_RIGHT(1),
  RIGHT(2),
  SLIGHT_RIGHT(3),
  STRAIGHT(4),
  SLIGHT_LEFT(5),
  LEFT(6),
  SHARP_LEFT(7);

  companion object {
    fun ofRaw(raw: Int): ManeuverModifier? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RerouteState(val raw: Int) {
  IDLE(0),
  FETCHING(1),
  INTERRUPTED(2);

  companion object {
    fun ofRaw(raw: Int): RerouteState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Comprehensive route request options
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RouteOptions (
  /** List of coordinates as "lon,lat;lon,lat" string */
  val coordinates: String,
  /** Routing profile: driving-traffic, driving, walking, cycling */
  val profile: String? = null,
  /** Whether to return alternative routes */
  val alternatives: Boolean? = null,
  /** Language for instructions (e.g., "en", "es", "pt") */
  val language: String? = null,
  /** Include voice instructions */
  val voiceInstructions: Boolean? = null,
  /** Include banner instructions */
  val bannerInstructions: Boolean? = null,
  /** Units for voice instructions */
  val voiceUnits: VoiceUnits? = null,
  /** Include step-by-step instructions */
  val steps: Boolean? = null,
  /** Continue in same direction of travel */
  val continueStraight: Boolean? = null,
  /** Semicolon-separated list of waypoint names */
  val waypointNames: String? = null,
  /** Semicolon-separated indices for waypoints (vs pass-through) */
  val waypointIndices: String? = null,
  /** Exclude road types (e.g., "toll,ferry") */
  val exclude: String? = null,
  /** Include road types */
  val include: String? = null,
  /** Enable route refresh for live traffic */
  val enableRefresh: Boolean? = null,
  /** Walking speed in m/s */
  val walkingSpeed: Double? = null,
  /** Max vehicle height in meters */
  val maxHeight: Double? = null,
  /** Max vehicle width in meters */
  val maxWidth: Double? = null,
  /** Max vehicle weight in metric tons */
  val maxWeight: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteOptions {
      val coordinates = pigeonVar_list[0] as String
      val profile = pigeonVar_list[1] as String?
      val alternatives = pigeonVar_list[2] as Boolean?
      val language = pigeonVar_list[3] as String?
      val voiceInstructions = pigeonVar_list[4] as Boolean?
      val bannerInstructions = pigeonVar_list[5] as Boolean?
      val voiceUnits = pigeonVar_list[6] as VoiceUnits?
      val steps = pigeonVar_list[7] as Boolean?
      val continueStraight = pigeonVar_list[8] as Boolean?
      val waypointNames = pigeonVar_list[9] as String?
      val waypointIndices = pigeonVar_list[10] as String?
      val exclude = pigeonVar_list[11] as String?
      val include = pigeonVar_list[12] as String?
      val enableRefresh = pigeonVar_list[13] as Boolean?
      val walkingSpeed = pigeonVar_list[14] as Double?
      val maxHeight = pigeonVar_list[15] as Double?
      val maxWidth = pigeonVar_list[16] as Double?
      val maxWeight = pigeonVar_list[17] as Double?
      return RouteOptions(coordinates, profile, alternatives, language, voiceInstructions, bannerInstructions, voiceUnits, steps, continueStraight, waypointNames, waypointIndices, exclude, include, enableRefresh, walkingSpeed, maxHeight, maxWidth, maxWeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      coordinates,
      profile,
      alternatives,
      language,
      voiceInstructions,
      bannerInstructions,
      voiceUnits,
      steps,
      continueStraight,
      waypointNames,
      waypointIndices,
      exclude,
      include,
      enableRefresh,
      walkingSpeed,
      maxHeight,
      maxWidth,
      maxWeight,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RouteOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Navigation session configuration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NavigationOptions (
  /** Automatically reroute when off-route */
  val enableReroute: Boolean? = null,
  /** Deviation threshold in meters to trigger reroute */
  val rerouteThreshold: Double? = null,
  /** Detect and suggest faster routes */
  val enableFasterRoute: Boolean? = null,
  /** Interval to check for faster routes (in seconds) */
  val fasterRouteDetectionInterval: Long? = null,
  /** Initial camera mode */
  val initialCameraMode: CameraMode? = null,
  /** Default camera padding (top, left, bottom, right) */
  val defaultPadding: CameraPadding? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavigationOptions {
      val enableReroute = pigeonVar_list[0] as Boolean?
      val rerouteThreshold = pigeonVar_list[1] as Double?
      val enableFasterRoute = pigeonVar_list[2] as Boolean?
      val fasterRouteDetectionInterval = pigeonVar_list[3] as Long?
      val initialCameraMode = pigeonVar_list[4] as CameraMode?
      val defaultPadding = pigeonVar_list[5] as CameraPadding?
      return NavigationOptions(enableReroute, rerouteThreshold, enableFasterRoute, fasterRouteDetectionInterval, initialCameraMode, defaultPadding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enableReroute,
      rerouteThreshold,
      enableFasterRoute,
      fasterRouteDetectionInterval,
      initialCameraMode,
      defaultPadding,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NavigationOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraPadding (
  val top: Double,
  val left: Double,
  val bottom: Double,
  val right: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraPadding {
      val top = pigeonVar_list[0] as Double
      val left = pigeonVar_list[1] as Double
      val bottom = pigeonVar_list[2] as Double
      val right = pigeonVar_list[3] as Double
      return CameraPadding(top, left, bottom, right)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      top,
      left,
      bottom,
      right,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CameraPadding) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for route line appearance
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RouteLineOptions (
  /** Primary route color (ARGB as int) */
  val primaryRouteColor: Long? = null,
  /** Alternative routes color */
  val alternativeRouteColor: Long? = null,
  /** Color for traveled portion of route */
  val traveledRouteColor: Long? = null,
  /** Width of primary route line */
  val routeLineWidth: Double? = null,
  /** Width of alternative route lines */
  val alternativeRouteLineWidth: Double? = null,
  /** Traffic congestion colors */
  val trafficUnknownColor: Long? = null,
  val trafficLowColor: Long? = null,
  val trafficModerateColor: Long? = null,
  val trafficHeavyColor: Long? = null,
  val trafficSevereColor: Long? = null,
  /** Enable traffic-based coloring */
  val enableTrafficColors: Boolean? = null,
  /** Enable vanishing route line (traveled portion fades) */
  val enableVanishingRouteLine: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteLineOptions {
      val primaryRouteColor = pigeonVar_list[0] as Long?
      val alternativeRouteColor = pigeonVar_list[1] as Long?
      val traveledRouteColor = pigeonVar_list[2] as Long?
      val routeLineWidth = pigeonVar_list[3] as Double?
      val alternativeRouteLineWidth = pigeonVar_list[4] as Double?
      val trafficUnknownColor = pigeonVar_list[5] as Long?
      val trafficLowColor = pigeonVar_list[6] as Long?
      val trafficModerateColor = pigeonVar_list[7] as Long?
      val trafficHeavyColor = pigeonVar_list[8] as Long?
      val trafficSevereColor = pigeonVar_list[9] as Long?
      val enableTrafficColors = pigeonVar_list[10] as Boolean?
      val enableVanishingRouteLine = pigeonVar_list[11] as Boolean?
      return RouteLineOptions(primaryRouteColor, alternativeRouteColor, traveledRouteColor, routeLineWidth, alternativeRouteLineWidth, trafficUnknownColor, trafficLowColor, trafficModerateColor, trafficHeavyColor, trafficSevereColor, enableTrafficColors, enableVanishingRouteLine)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primaryRouteColor,
      alternativeRouteColor,
      traveledRouteColor,
      routeLineWidth,
      alternativeRouteLineWidth,
      trafficUnknownColor,
      trafficLowColor,
      trafficModerateColor,
      trafficHeavyColor,
      trafficSevereColor,
      enableTrafficColors,
      enableVanishingRouteLine,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RouteLineOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for maneuver arrow appearance
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ManeuverArrowOptions (
  /** Arrow fill color (ARGB) */
  val arrowColor: Long? = null,
  /** Arrow border color (ARGB) */
  val arrowBorderColor: Long? = null,
  /** Border width in pixels */
  val arrowBorderWidth: Double? = null,
  /** Length of arrow shaft */
  val arrowShaftLength: Double? = null,
  /** Length of arrow head */
  val arrowHeadLength: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ManeuverArrowOptions {
      val arrowColor = pigeonVar_list[0] as Long?
      val arrowBorderColor = pigeonVar_list[1] as Long?
      val arrowBorderWidth = pigeonVar_list[2] as Double?
      val arrowShaftLength = pigeonVar_list[3] as Double?
      val arrowHeadLength = pigeonVar_list[4] as Double?
      return ManeuverArrowOptions(arrowColor, arrowBorderColor, arrowBorderWidth, arrowShaftLength, arrowHeadLength)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      arrowColor,
      arrowBorderColor,
      arrowBorderWidth,
      arrowShaftLength,
      arrowHeadLength,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ManeuverArrowOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Camera animation configuration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CameraAnimationOptions (
  /** Animation duration in milliseconds */
  val duration: Long? = null,
  /** Maximum duration in milliseconds */
  val maxDuration: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraAnimationOptions {
      val duration = pigeonVar_list[0] as Long?
      val maxDuration = pigeonVar_list[1] as Long?
      return CameraAnimationOptions(duration, maxDuration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      duration,
      maxDuration,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CameraAnimationOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Lane guidance information for an intersection
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LaneInfo (
  /** List of lanes at this intersection */
  val lanes: List<Lane>,
  /** Primary active direction (e.g., "straight", "left") */
  val activeDirection: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LaneInfo {
      val lanes = pigeonVar_list[0] as List<Lane>
      val activeDirection = pigeonVar_list[1] as String?
      return LaneInfo(lanes, activeDirection)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lanes,
      activeDirection,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LaneInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Individual lane information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Lane (
  /** Whether this lane can be used */
  val valid: Boolean,
  /** Whether this lane should be used */
  val active: Boolean,
  /** Possible directions from this lane (straight, left, right, slight_left, etc.) */
  val directions: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Lane {
      val valid = pigeonVar_list[0] as Boolean
      val active = pigeonVar_list[1] as Boolean
      val directions = pigeonVar_list[2] as List<String>
      return Lane(valid, active, directions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      valid,
      active,
      directions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Lane) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Real-time route progress information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RouteProgress (
  /** Distance remaining to destination in meters */
  val distanceRemaining: Double,
  /** Time remaining to destination in seconds */
  val durationRemaining: Double,
  /** Distance traveled so far in meters */
  val distanceTraveled: Double,
  /** Fraction of route traveled (0.0 to 1.0) */
  val fractionTraveled: Double,
  /** Index of current step */
  val currentStepIndex: Long? = null,
  /** Index of current leg */
  val currentLegIndex: Long? = null,
  /** Index of upcoming step */
  val upcomingStepIndex: Long? = null,
  /** Current step details */
  val currentStep: RouteStep? = null,
  /** Upcoming step details */
  val upcomingStep: RouteStep? = null,
  /** Current road/street name */
  val currentRoadName: String? = null,
  /** Current speed limit in km/h (null if unknown) */
  val currentSpeedLimit: Double? = null,
  /** Traffic congestion level: unknown, low, moderate, heavy, severe */
  val congestionLevel: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteProgress {
      val distanceRemaining = pigeonVar_list[0] as Double
      val durationRemaining = pigeonVar_list[1] as Double
      val distanceTraveled = pigeonVar_list[2] as Double
      val fractionTraveled = pigeonVar_list[3] as Double
      val currentStepIndex = pigeonVar_list[4] as Long?
      val currentLegIndex = pigeonVar_list[5] as Long?
      val upcomingStepIndex = pigeonVar_list[6] as Long?
      val currentStep = pigeonVar_list[7] as RouteStep?
      val upcomingStep = pigeonVar_list[8] as RouteStep?
      val currentRoadName = pigeonVar_list[9] as String?
      val currentSpeedLimit = pigeonVar_list[10] as Double?
      val congestionLevel = pigeonVar_list[11] as String?
      return RouteProgress(distanceRemaining, durationRemaining, distanceTraveled, fractionTraveled, currentStepIndex, currentLegIndex, upcomingStepIndex, currentStep, upcomingStep, currentRoadName, currentSpeedLimit, congestionLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      distanceRemaining,
      durationRemaining,
      distanceTraveled,
      fractionTraveled,
      currentStepIndex,
      currentLegIndex,
      upcomingStepIndex,
      currentStep,
      upcomingStep,
      currentRoadName,
      currentSpeedLimit,
      congestionLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RouteProgress) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RouteStep (
  /** Distance of this step in meters */
  val distance: Double,
  /** Duration of this step in seconds */
  val duration: Double,
  /** Street/road name */
  val name: String? = null,
  /** Human-readable instruction */
  val instruction: String? = null,
  /** Type of maneuver */
  val maneuverType: ManeuverType? = null,
  /** Modifier for maneuver */
  val maneuverModifier: ManeuverModifier? = null,
  /** Distance to the maneuver in meters */
  val distanceToManeuver: Double? = null,
  /** Time to the maneuver in seconds */
  val estimatedTimeToManeuver: Double? = null,
  /** Exit numbers (for roundabouts/intersections) */
  val exitNumbers: String? = null,
  /** Lane guidance information (Sprint 2) */
  val laneInfo: LaneInfo? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteStep {
      val distance = pigeonVar_list[0] as Double
      val duration = pigeonVar_list[1] as Double
      val name = pigeonVar_list[2] as String?
      val instruction = pigeonVar_list[3] as String?
      val maneuverType = pigeonVar_list[4] as ManeuverType?
      val maneuverModifier = pigeonVar_list[5] as ManeuverModifier?
      val distanceToManeuver = pigeonVar_list[6] as Double?
      val estimatedTimeToManeuver = pigeonVar_list[7] as Double?
      val exitNumbers = pigeonVar_list[8] as String?
      val laneInfo = pigeonVar_list[9] as LaneInfo?
      return RouteStep(distance, duration, name, instruction, maneuverType, maneuverModifier, distanceToManeuver, estimatedTimeToManeuver, exitNumbers, laneInfo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      distance,
      duration,
      name,
      instruction,
      maneuverType,
      maneuverModifier,
      distanceToManeuver,
      estimatedTimeToManeuver,
      exitNumbers,
      laneInfo,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RouteStep) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Banner instruction for visual guidance
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BannerInstruction (
  /** Main instruction text */
  val primaryText: String,
  /** Additional instruction text */
  val secondaryText: String? = null,
  /** Distance to maneuver in meters */
  val distanceToManeuver: Double? = null,
  /** Type of maneuver */
  val maneuverType: ManeuverType? = null,
  /** Modifier for maneuver */
  val maneuverModifier: ManeuverModifier? = null,
  /** Driving side: left or right */
  val drivingSide: String? = null,
  /** Heading change in degrees */
  val degrees: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BannerInstruction {
      val primaryText = pigeonVar_list[0] as String
      val secondaryText = pigeonVar_list[1] as String?
      val distanceToManeuver = pigeonVar_list[2] as Double?
      val maneuverType = pigeonVar_list[3] as ManeuverType?
      val maneuverModifier = pigeonVar_list[4] as ManeuverModifier?
      val drivingSide = pigeonVar_list[5] as String?
      val degrees = pigeonVar_list[6] as Double?
      return BannerInstruction(primaryText, secondaryText, distanceToManeuver, maneuverType, maneuverModifier, drivingSide, degrees)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primaryText,
      secondaryText,
      distanceToManeuver,
      maneuverType,
      maneuverModifier,
      drivingSide,
      degrees,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BannerInstruction) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Voice instruction for audio guidance
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VoiceInstruction (
  /** Plain text announcement */
  val announcement: String,
  /** SSML-formatted announcement */
  val ssmlAnnouncement: String,
  /** Distance along geometry where this should be announced */
  val distanceAlongGeometry: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VoiceInstruction {
      val announcement = pigeonVar_list[0] as String
      val ssmlAnnouncement = pigeonVar_list[1] as String
      val distanceAlongGeometry = pigeonVar_list[2] as Double?
      return VoiceInstruction(announcement, ssmlAnnouncement, distanceAlongGeometry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      announcement,
      ssmlAnnouncement,
      distanceAlongGeometry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VoiceInstruction) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Alternative route information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RouteAlternative (
  /** Alternative route identifier */
  val id: String,
  /** Total distance in meters */
  val distance: Double,
  /** Total duration in seconds */
  val duration: Double,
  /** Distance difference from current route */
  val distanceDelta: Double? = null,
  /** Duration difference from current route */
  val durationDelta: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteAlternative {
      val id = pigeonVar_list[0] as String
      val distance = pigeonVar_list[1] as Double
      val duration = pigeonVar_list[2] as Double
      val distanceDelta = pigeonVar_list[3] as Double?
      val durationDelta = pigeonVar_list[4] as Double?
      return RouteAlternative(id, distance, duration, distanceDelta, durationDelta)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      distance,
      duration,
      distanceDelta,
      durationDelta,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RouteAlternative) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Location with enhanced matching data
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EnhancedLocation (
  val latitude: Double,
  val longitude: Double,
  val bearing: Double? = null,
  val speed: Double? = null,
  val altitude: Double? = null,
  val accuracy: Double? = null,
  val timestamp: Long? = null,
  val isMatched: Boolean? = null,
  val roadName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EnhancedLocation {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val bearing = pigeonVar_list[2] as Double?
      val speed = pigeonVar_list[3] as Double?
      val altitude = pigeonVar_list[4] as Double?
      val accuracy = pigeonVar_list[5] as Double?
      val timestamp = pigeonVar_list[6] as Long?
      val isMatched = pigeonVar_list[7] as Boolean?
      val roadName = pigeonVar_list[8] as String?
      return EnhancedLocation(latitude, longitude, bearing, speed, altitude, accuracy, timestamp, isMatched, roadName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      bearing,
      speed,
      altitude,
      accuracy,
      timestamp,
      isMatched,
      roadName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is EnhancedLocation) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RouteProgressEvent (
  val progress: RouteProgress,
  val timestamp: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RouteProgressEvent {
      val progress = pigeonVar_list[0] as RouteProgress
      val timestamp = pigeonVar_list[1] as Long
      return RouteProgressEvent(progress, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      progress,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RouteProgressEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RerouteEvent (
  val reason: String,
  val state: RerouteState,
  val newRoute: RouteAlternative? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RerouteEvent {
      val reason = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as RerouteState
      val newRoute = pigeonVar_list[2] as RouteAlternative?
      return RerouteEvent(reason, state, newRoute)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reason,
      state,
      newRoute,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RerouteEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ArrivalEvent (
  val finalDestination: Boolean,
  val waypointIndex: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ArrivalEvent {
      val finalDestination = pigeonVar_list[0] as Boolean
      val waypointIndex = pigeonVar_list[1] as Long?
      return ArrivalEvent(finalDestination, waypointIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      finalDestination,
      waypointIndex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ArrivalEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OffRouteEvent (
  val distanceFromRoute: Double,
  val timestamp: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OffRouteEvent {
      val distanceFromRoute = pigeonVar_list[0] as Double
      val timestamp = pigeonVar_list[1] as Long
      return OffRouteEvent(distanceFromRoute, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      distanceFromRoute,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OffRouteEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NavigationStateEvent (
  val state: NavigationState,
  val timestamp: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavigationStateEvent {
      val state = pigeonVar_list[0] as NavigationState
      val timestamp = pigeonVar_list[1] as Long
      return NavigationStateEvent(state, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NavigationStateEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return NavigationInterfacesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NavigationInterfacesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NavigationState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraMode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VoiceUnits.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ManeuverType.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ManeuverModifier.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RerouteState.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteOptions.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NavigationOptions.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraPadding.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteLineOptions.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ManeuverArrowOptions.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraAnimationOptions.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LaneInfo.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Lane.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteProgress.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteStep.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BannerInstruction.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoiceInstruction.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteAlternative.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EnhancedLocation.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RouteProgressEvent.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RerouteEvent.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ArrivalEvent.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OffRouteEvent.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NavigationStateEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NavigationState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CameraMode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is VoiceUnits -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ManeuverType -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ManeuverModifier -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is RerouteState -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is RouteOptions -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NavigationOptions -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CameraPadding -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is RouteLineOptions -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is ManeuverArrowOptions -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is CameraAnimationOptions -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is LaneInfo -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is Lane -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is RouteProgress -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is RouteStep -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is BannerInstruction -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is VoiceInstruction -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is RouteAlternative -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is EnhancedLocation -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is RouteProgressEvent -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is RerouteEvent -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is ArrivalEvent -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is OffRouteEvent -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is NavigationStateEvent -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NavigationInterface {
  /** Start a navigation session with options */
  fun startNavigation(options: NavigationOptions, callback: (Result<Boolean>) -> Unit)
  /** Stop the current navigation session */
  fun stopNavigation(callback: (Result<Boolean>) -> Unit)
  /** Pause navigation (keep session alive but stop guidance) */
  fun pauseNavigation(callback: (Result<Boolean>) -> Unit)
  /** Resume paused navigation */
  fun resumeNavigation(callback: (Result<Boolean>) -> Unit)
  /** Get current navigation state */
  fun getNavigationState(): NavigationState
  /** Request and set a route */
  fun setRoute(options: RouteOptions, callback: (Result<Boolean>) -> Unit)
  /** Clear current route */
  fun clearRoute(callback: (Result<Boolean>) -> Unit)
  /** Request route alternatives */
  fun getRouteAlternatives(callback: (Result<List<RouteAlternative>>) -> Unit)
  /** Select an alternative route by ID */
  fun selectAlternativeRoute(routeId: String, callback: (Result<Boolean>) -> Unit)
  /** Get current route progress (returns null if no active route) */
  fun getCurrentProgress(): RouteProgress?
  /** Get current location with map matching */
  fun getCurrentLocation(): EnhancedLocation?
  /** Set camera mode */
  fun setCameraMode(mode: CameraMode)
  /** Get current camera mode */
  fun getCameraMode(): CameraMode
  /** Update camera padding */
  fun setCameraPadding(padding: CameraPadding)
  /** Mute or unmute voice instructions */
  fun setVoiceMuted(muted: Boolean)
  /** Check if voice is muted */
  fun isVoiceMuted(): Boolean
  /** Set voice language (e.g., "en", "es", "pt") */
  fun setVoiceLanguage(languageCode: String)
  /** Set voice units */
  fun setVoiceUnits(units: VoiceUnits)
  /** Register for route progress events */
  fun registerProgressObserver()
  /** Unregister from route progress events */
  fun unregisterProgressObserver()
  /** Register for banner instruction events */
  fun registerBannerObserver()
  /** Unregister from banner instruction events */
  fun unregisterBannerObserver()
  /** Register for voice instruction events */
  fun registerVoiceObserver()
  /** Unregister from voice instruction events */
  fun unregisterVoiceObserver()
  /** Register for reroute events */
  fun registerRerouteObserver()
  /** Unregister from reroute events */
  fun unregisterRerouteObserver()
  /** Register for arrival events */
  fun registerArrivalObserver()
  /** Unregister from arrival events */
  fun unregisterArrivalObserver()
  /** Register for off-route events */
  fun registerOffRouteObserver()
  /** Unregister from off-route events */
  fun unregisterOffRouteObserver()
  /** Set route line styling options */
  fun setRouteLineOptions(options: RouteLineOptions)
  /** Get current route line options */
  fun getRouteLineOptions(): RouteLineOptions
  /** Set maneuver arrow styling options */
  fun setManeuverArrowOptions(options: ManeuverArrowOptions)
  /** Get current maneuver arrow options */
  fun getManeuverArrowOptions(): ManeuverArrowOptions
  /** Set camera mode with animation */
  fun setCameraModeAnimated(mode: CameraMode, options: CameraAnimationOptions)

  companion object {
    /** The codec used by NavigationInterface. */
    val codec: MessageCodec<Any?> by lazy {
      NavigationInterfacesPigeonCodec()
    }
    /** Sets up an instance of `NavigationInterface` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NavigationInterface?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.startNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as NavigationOptions
            api.startNavigation(optionsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.stopNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopNavigation{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.pauseNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pauseNavigation{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.resumeNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.resumeNavigation{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getNavigationState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNavigationState())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as RouteOptions
            api.setRoute(optionsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.clearRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearRoute{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getRouteAlternatives$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRouteAlternatives{ result: Result<List<RouteAlternative>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.selectAlternativeRoute$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeIdArg = args[0] as String
            api.selectAlternativeRoute(routeIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationInterfacesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationInterfacesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getCurrentProgress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentProgress())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getCurrentLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentLocation())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setCameraMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as CameraMode
            val wrapped: List<Any?> = try {
              api.setCameraMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getCameraMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCameraMode())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setCameraPadding$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paddingArg = args[0] as CameraPadding
            val wrapped: List<Any?> = try {
              api.setCameraPadding(paddingArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setVoiceMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mutedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setVoiceMuted(mutedArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.isVoiceMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isVoiceMuted())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setVoiceLanguage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val languageCodeArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setVoiceLanguage(languageCodeArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setVoiceUnits$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val unitsArg = args[0] as VoiceUnits
            val wrapped: List<Any?> = try {
              api.setVoiceUnits(unitsArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerProgressObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.registerProgressObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterProgressObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterProgressObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerBannerObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.registerBannerObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterBannerObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterBannerObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerVoiceObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.registerVoiceObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterVoiceObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterVoiceObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerRerouteObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.registerRerouteObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterRerouteObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterRerouteObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerArrivalObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.registerArrivalObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterArrivalObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterArrivalObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerOffRouteObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.registerOffRouteObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterOffRouteObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterOffRouteObserver()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setRouteLineOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as RouteLineOptions
            val wrapped: List<Any?> = try {
              api.setRouteLineOptions(optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getRouteLineOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRouteLineOptions())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setManeuverArrowOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as ManeuverArrowOptions
            val wrapped: List<Any?> = try {
              api.setManeuverArrowOptions(optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getManeuverArrowOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getManeuverArrowOptions())
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setCameraModeAnimated$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as CameraMode
            val optionsArg = args[1] as CameraAnimationOptions
            val wrapped: List<Any?> = try {
              api.setCameraModeAnimated(modeArg, optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              NavigationInterfacesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NavigationEventListener(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NavigationEventListener. */
    val codec: MessageCodec<Any?> by lazy {
      NavigationInterfacesPigeonCodec()
    }
  }
  /** Called when route progress updates */
  fun onRouteProgress(eventArg: RouteProgressEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onRouteProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when banner instruction should be displayed */
  fun onBannerInstruction(instructionArg: BannerInstruction, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onBannerInstruction$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(instructionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when voice instruction should be spoken */
  fun onVoiceInstruction(instructionArg: VoiceInstruction, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onVoiceInstruction$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(instructionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called during reroute process */
  fun onReroute(eventArg: RerouteEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onReroute$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when arriving at waypoint or destination */
  fun onArrival(eventArg: ArrivalEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onArrival$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when driver goes off route */
  fun onOffRoute(eventArg: OffRouteEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onOffRoute$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when navigation state changes */
  fun onNavigationStateChanged(eventArg: NavigationStateEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onNavigationStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(NavigationFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NavigationInterfacesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
