// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

part of mapbox_maps_flutter;

PlatformException _navigationCreateConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> _navigationWrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _navigationDeepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

enum NavigationState {
  idle,
  freeDrive,
  activeGuidance,
  arrived,
  stopped,
}

enum CameraMode {
  idle,
  overview,
  following,
}

enum VoiceUnits {
  imperial,
  metric,
}

enum ManeuverType {
  turn,
  newName,
  depart,
  arrive,
  merge,
  onRamp,
  offRamp,
  fork,
  endOfRoad,
  continue_,
  roundabout,
  rotary,
  roundaboutTurn,
  notification,
  exitRoundabout,
  exitRotary,
}

enum ManeuverModifier {
  uturn,
  sharpRight,
  right,
  slightRight,
  straight,
  slightLeft,
  left,
  sharpLeft,
}

enum RerouteState {
  idle,
  fetching,
  interrupted,
}

/// Comprehensive route request options
class RouteOptions {
  RouteOptions({
    required this.coordinates,
    this.profile,
    this.alternatives,
    this.language,
    this.voiceInstructions,
    this.bannerInstructions,
    this.voiceUnits,
    this.steps,
    this.continueStraight,
    this.waypointNames,
    this.waypointIndices,
    this.exclude,
    this.include,
    this.enableRefresh,
    this.walkingSpeed,
    this.maxHeight,
    this.maxWidth,
    this.maxWeight,
  });

  /// List of coordinates as "lon,lat;lon,lat" string
  String coordinates;

  /// Routing profile: driving-traffic, driving, walking, cycling
  String? profile;

  /// Whether to return alternative routes
  bool? alternatives;

  /// Language for instructions (e.g., "en", "es", "pt")
  String? language;

  /// Include voice instructions
  bool? voiceInstructions;

  /// Include banner instructions
  bool? bannerInstructions;

  /// Units for voice instructions
  VoiceUnits? voiceUnits;

  /// Include step-by-step instructions
  bool? steps;

  /// Continue in same direction of travel
  bool? continueStraight;

  /// Semicolon-separated list of waypoint names
  String? waypointNames;

  /// Semicolon-separated indices for waypoints (vs pass-through)
  String? waypointIndices;

  /// Exclude road types (e.g., "toll,ferry")
  String? exclude;

  /// Include road types
  String? include;

  /// Enable route refresh for live traffic
  bool? enableRefresh;

  /// Walking speed in m/s
  double? walkingSpeed;

  /// Max vehicle height in meters
  double? maxHeight;

  /// Max vehicle width in meters
  double? maxWidth;

  /// Max vehicle weight in metric tons
  double? maxWeight;

  List<Object?> _toList() {
    return <Object?>[
      coordinates,
      profile,
      alternatives,
      language,
      voiceInstructions,
      bannerInstructions,
      voiceUnits,
      steps,
      continueStraight,
      waypointNames,
      waypointIndices,
      exclude,
      include,
      enableRefresh,
      walkingSpeed,
      maxHeight,
      maxWidth,
      maxWeight,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RouteOptions decode(Object result) {
    result as List<Object?>;
    return RouteOptions(
      coordinates: result[0]! as String,
      profile: result[1] as String?,
      alternatives: result[2] as bool?,
      language: result[3] as String?,
      voiceInstructions: result[4] as bool?,
      bannerInstructions: result[5] as bool?,
      voiceUnits: result[6] as VoiceUnits?,
      steps: result[7] as bool?,
      continueStraight: result[8] as bool?,
      waypointNames: result[9] as String?,
      waypointIndices: result[10] as String?,
      exclude: result[11] as String?,
      include: result[12] as String?,
      enableRefresh: result[13] as bool?,
      walkingSpeed: result[14] as double?,
      maxHeight: result[15] as double?,
      maxWidth: result[16] as double?,
      maxWeight: result[17] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Navigation session configuration
class NavigationOptions {
  NavigationOptions({
    this.enableReroute,
    this.rerouteThreshold,
    this.enableFasterRoute,
    this.fasterRouteDetectionInterval,
    this.initialCameraMode,
    this.defaultPadding,
  });

  /// Automatically reroute when off-route
  bool? enableReroute;

  /// Deviation threshold in meters to trigger reroute
  double? rerouteThreshold;

  /// Detect and suggest faster routes
  bool? enableFasterRoute;

  /// Interval to check for faster routes (in seconds)
  int? fasterRouteDetectionInterval;

  /// Initial camera mode
  CameraMode? initialCameraMode;

  /// Default camera padding (top, left, bottom, right)
  CameraPadding? defaultPadding;

  List<Object?> _toList() {
    return <Object?>[
      enableReroute,
      rerouteThreshold,
      enableFasterRoute,
      fasterRouteDetectionInterval,
      initialCameraMode,
      defaultPadding,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NavigationOptions decode(Object result) {
    result as List<Object?>;
    return NavigationOptions(
      enableReroute: result[0] as bool?,
      rerouteThreshold: result[1] as double?,
      enableFasterRoute: result[2] as bool?,
      fasterRouteDetectionInterval: result[3] as int?,
      initialCameraMode: result[4] as CameraMode?,
      defaultPadding: result[5] as CameraPadding?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class CameraPadding {
  CameraPadding({
    required this.top,
    required this.left,
    required this.bottom,
    required this.right,
  });

  double top;

  double left;

  double bottom;

  double right;

  List<Object?> _toList() {
    return <Object?>[
      top,
      left,
      bottom,
      right,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CameraPadding decode(Object result) {
    result as List<Object?>;
    return CameraPadding(
      top: result[0]! as double,
      left: result[1]! as double,
      bottom: result[2]! as double,
      right: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraPadding || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for route line appearance
class RouteLineOptions {
  RouteLineOptions({
    this.primaryRouteColor,
    this.alternativeRouteColor,
    this.traveledRouteColor,
    this.routeLineWidth,
    this.alternativeRouteLineWidth,
    this.trafficUnknownColor,
    this.trafficLowColor,
    this.trafficModerateColor,
    this.trafficHeavyColor,
    this.trafficSevereColor,
    this.enableTrafficColors,
    this.enableVanishingRouteLine,
  });

  /// Primary route color (ARGB as int)
  int? primaryRouteColor;

  /// Alternative routes color
  int? alternativeRouteColor;

  /// Color for traveled portion of route
  int? traveledRouteColor;

  /// Width of primary route line
  double? routeLineWidth;

  /// Width of alternative route lines
  double? alternativeRouteLineWidth;

  /// Traffic congestion colors
  int? trafficUnknownColor;

  int? trafficLowColor;

  int? trafficModerateColor;

  int? trafficHeavyColor;

  int? trafficSevereColor;

  /// Enable traffic-based coloring
  bool? enableTrafficColors;

  /// Enable vanishing route line (traveled portion fades)
  bool? enableVanishingRouteLine;

  List<Object?> _toList() {
    return <Object?>[
      primaryRouteColor,
      alternativeRouteColor,
      traveledRouteColor,
      routeLineWidth,
      alternativeRouteLineWidth,
      trafficUnknownColor,
      trafficLowColor,
      trafficModerateColor,
      trafficHeavyColor,
      trafficSevereColor,
      enableTrafficColors,
      enableVanishingRouteLine,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RouteLineOptions decode(Object result) {
    result as List<Object?>;
    return RouteLineOptions(
      primaryRouteColor: result[0] as int?,
      alternativeRouteColor: result[1] as int?,
      traveledRouteColor: result[2] as int?,
      routeLineWidth: result[3] as double?,
      alternativeRouteLineWidth: result[4] as double?,
      trafficUnknownColor: result[5] as int?,
      trafficLowColor: result[6] as int?,
      trafficModerateColor: result[7] as int?,
      trafficHeavyColor: result[8] as int?,
      trafficSevereColor: result[9] as int?,
      enableTrafficColors: result[10] as bool?,
      enableVanishingRouteLine: result[11] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteLineOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for maneuver arrow appearance
class ManeuverArrowOptions {
  ManeuverArrowOptions({
    this.arrowColor,
    this.arrowBorderColor,
    this.arrowBorderWidth,
    this.arrowShaftLength,
    this.arrowHeadLength,
  });

  /// Arrow fill color (ARGB)
  int? arrowColor;

  /// Arrow border color (ARGB)
  int? arrowBorderColor;

  /// Border width in pixels
  double? arrowBorderWidth;

  /// Length of arrow shaft
  double? arrowShaftLength;

  /// Length of arrow head
  double? arrowHeadLength;

  List<Object?> _toList() {
    return <Object?>[
      arrowColor,
      arrowBorderColor,
      arrowBorderWidth,
      arrowShaftLength,
      arrowHeadLength,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ManeuverArrowOptions decode(Object result) {
    result as List<Object?>;
    return ManeuverArrowOptions(
      arrowColor: result[0] as int?,
      arrowBorderColor: result[1] as int?,
      arrowBorderWidth: result[2] as double?,
      arrowShaftLength: result[3] as double?,
      arrowHeadLength: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ManeuverArrowOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Camera animation configuration
class CameraAnimationOptions {
  CameraAnimationOptions({
    this.duration,
    this.maxDuration,
  });

  /// Animation duration in milliseconds
  int? duration;

  /// Maximum duration in milliseconds
  int? maxDuration;

  List<Object?> _toList() {
    return <Object?>[
      duration,
      maxDuration,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CameraAnimationOptions decode(Object result) {
    result as List<Object?>;
    return CameraAnimationOptions(
      duration: result[0] as int?,
      maxDuration: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraAnimationOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Lane guidance information for an intersection
class LaneInfo {
  LaneInfo({
    required this.lanes,
    this.activeDirection,
  });

  /// List of lanes at this intersection
  List<Lane> lanes;

  /// Primary active direction (e.g., "straight", "left")
  String? activeDirection;

  List<Object?> _toList() {
    return <Object?>[
      lanes,
      activeDirection,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LaneInfo decode(Object result) {
    result as List<Object?>;
    return LaneInfo(
      lanes: (result[0] as List<Object?>?)!.cast<Lane>(),
      activeDirection: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LaneInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Individual lane information
class Lane {
  Lane({
    required this.valid,
    required this.active,
    required this.directions,
  });

  /// Whether this lane can be used
  bool valid;

  /// Whether this lane should be used
  bool active;

  /// Possible directions from this lane (straight, left, right, slight_left, etc.)
  List<String> directions;

  List<Object?> _toList() {
    return <Object?>[
      valid,
      active,
      directions,
    ];
  }

  Object encode() {
    return _toList();
  }

  static Lane decode(Object result) {
    result as List<Object?>;
    return Lane(
      valid: result[0]! as bool,
      active: result[1]! as bool,
      directions: (result[2] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Lane || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Real-time route progress information
class RouteProgress {
  RouteProgress({
    required this.distanceRemaining,
    required this.durationRemaining,
    required this.distanceTraveled,
    required this.fractionTraveled,
    this.currentStepIndex,
    this.currentLegIndex,
    this.upcomingStepIndex,
    this.currentStep,
    this.upcomingStep,
    this.currentRoadName,
    this.currentSpeedLimit,
    this.congestionLevel,
  });

  /// Distance remaining to destination in meters
  double distanceRemaining;

  /// Time remaining to destination in seconds
  double durationRemaining;

  /// Distance traveled so far in meters
  double distanceTraveled;

  /// Fraction of route traveled (0.0 to 1.0)
  double fractionTraveled;

  /// Index of current step
  int? currentStepIndex;

  /// Index of current leg
  int? currentLegIndex;

  /// Index of upcoming step
  int? upcomingStepIndex;

  /// Current step details
  RouteStep? currentStep;

  /// Upcoming step details
  RouteStep? upcomingStep;

  /// Current road/street name
  String? currentRoadName;

  /// Current speed limit in km/h (null if unknown)
  double? currentSpeedLimit;

  /// Traffic congestion level: unknown, low, moderate, heavy, severe
  String? congestionLevel;

  List<Object?> _toList() {
    return <Object?>[
      distanceRemaining,
      durationRemaining,
      distanceTraveled,
      fractionTraveled,
      currentStepIndex,
      currentLegIndex,
      upcomingStepIndex,
      currentStep,
      upcomingStep,
      currentRoadName,
      currentSpeedLimit,
      congestionLevel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RouteProgress decode(Object result) {
    result as List<Object?>;
    return RouteProgress(
      distanceRemaining: result[0]! as double,
      durationRemaining: result[1]! as double,
      distanceTraveled: result[2]! as double,
      fractionTraveled: result[3]! as double,
      currentStepIndex: result[4] as int?,
      currentLegIndex: result[5] as int?,
      upcomingStepIndex: result[6] as int?,
      currentStep: result[7] as RouteStep?,
      upcomingStep: result[8] as RouteStep?,
      currentRoadName: result[9] as String?,
      currentSpeedLimit: result[10] as double?,
      congestionLevel: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RouteStep {
  RouteStep({
    required this.distance,
    required this.duration,
    this.name,
    this.instruction,
    this.maneuverType,
    this.maneuverModifier,
    this.distanceToManeuver,
    this.estimatedTimeToManeuver,
    this.exitNumbers,
    this.laneInfo,
  });

  /// Distance of this step in meters
  double distance;

  /// Duration of this step in seconds
  double duration;

  /// Street/road name
  String? name;

  /// Human-readable instruction
  String? instruction;

  /// Type of maneuver
  ManeuverType? maneuverType;

  /// Modifier for maneuver
  ManeuverModifier? maneuverModifier;

  /// Distance to the maneuver in meters
  double? distanceToManeuver;

  /// Time to the maneuver in seconds
  double? estimatedTimeToManeuver;

  /// Exit numbers (for roundabouts/intersections)
  String? exitNumbers;

  /// Lane guidance information (Sprint 2)
  LaneInfo? laneInfo;

  List<Object?> _toList() {
    return <Object?>[
      distance,
      duration,
      name,
      instruction,
      maneuverType,
      maneuverModifier,
      distanceToManeuver,
      estimatedTimeToManeuver,
      exitNumbers,
      laneInfo,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RouteStep decode(Object result) {
    result as List<Object?>;
    return RouteStep(
      distance: result[0]! as double,
      duration: result[1]! as double,
      name: result[2] as String?,
      instruction: result[3] as String?,
      maneuverType: result[4] as ManeuverType?,
      maneuverModifier: result[5] as ManeuverModifier?,
      distanceToManeuver: result[6] as double?,
      estimatedTimeToManeuver: result[7] as double?,
      exitNumbers: result[8] as String?,
      laneInfo: result[9] as LaneInfo?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteStep || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Banner instruction for visual guidance
class BannerInstruction {
  BannerInstruction({
    required this.primaryText,
    this.secondaryText,
    this.distanceToManeuver,
    this.maneuverType,
    this.maneuverModifier,
    this.drivingSide,
    this.degrees,
  });

  /// Main instruction text
  String primaryText;

  /// Additional instruction text
  String? secondaryText;

  /// Distance to maneuver in meters
  double? distanceToManeuver;

  /// Type of maneuver
  ManeuverType? maneuverType;

  /// Modifier for maneuver
  ManeuverModifier? maneuverModifier;

  /// Driving side: left or right
  String? drivingSide;

  /// Heading change in degrees
  double? degrees;

  List<Object?> _toList() {
    return <Object?>[
      primaryText,
      secondaryText,
      distanceToManeuver,
      maneuverType,
      maneuverModifier,
      drivingSide,
      degrees,
    ];
  }

  Object encode() {
    return _toList();
  }

  static BannerInstruction decode(Object result) {
    result as List<Object?>;
    return BannerInstruction(
      primaryText: result[0]! as String,
      secondaryText: result[1] as String?,
      distanceToManeuver: result[2] as double?,
      maneuverType: result[3] as ManeuverType?,
      maneuverModifier: result[4] as ManeuverModifier?,
      drivingSide: result[5] as String?,
      degrees: result[6] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BannerInstruction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Voice instruction for audio guidance
class VoiceInstruction {
  VoiceInstruction({
    required this.announcement,
    required this.ssmlAnnouncement,
    this.distanceAlongGeometry,
  });

  /// Plain text announcement
  String announcement;

  /// SSML-formatted announcement
  String ssmlAnnouncement;

  /// Distance along geometry where this should be announced
  double? distanceAlongGeometry;

  List<Object?> _toList() {
    return <Object?>[
      announcement,
      ssmlAnnouncement,
      distanceAlongGeometry,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VoiceInstruction decode(Object result) {
    result as List<Object?>;
    return VoiceInstruction(
      announcement: result[0]! as String,
      ssmlAnnouncement: result[1]! as String,
      distanceAlongGeometry: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VoiceInstruction || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Alternative route information
class RouteAlternative {
  RouteAlternative({
    required this.id,
    required this.distance,
    required this.duration,
    this.distanceDelta,
    this.durationDelta,
  });

  /// Alternative route identifier
  String id;

  /// Total distance in meters
  double distance;

  /// Total duration in seconds
  double duration;

  /// Distance difference from current route
  double? distanceDelta;

  /// Duration difference from current route
  double? durationDelta;

  List<Object?> _toList() {
    return <Object?>[
      id,
      distance,
      duration,
      distanceDelta,
      durationDelta,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RouteAlternative decode(Object result) {
    result as List<Object?>;
    return RouteAlternative(
      id: result[0]! as String,
      distance: result[1]! as double,
      duration: result[2]! as double,
      distanceDelta: result[3] as double?,
      durationDelta: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteAlternative || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Location with enhanced matching data
class EnhancedLocation {
  EnhancedLocation({
    required this.latitude,
    required this.longitude,
    this.bearing,
    this.speed,
    this.altitude,
    this.accuracy,
    this.timestamp,
    this.isMatched,
    this.roadName,
  });

  double latitude;

  double longitude;

  double? bearing;

  double? speed;

  double? altitude;

  double? accuracy;

  int? timestamp;

  bool? isMatched;

  String? roadName;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
      bearing,
      speed,
      altitude,
      accuracy,
      timestamp,
      isMatched,
      roadName,
    ];
  }

  Object encode() {
    return _toList();
  }

  static EnhancedLocation decode(Object result) {
    result as List<Object?>;
    return EnhancedLocation(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
      bearing: result[2] as double?,
      speed: result[3] as double?,
      altitude: result[4] as double?,
      accuracy: result[5] as double?,
      timestamp: result[6] as int?,
      isMatched: result[7] as bool?,
      roadName: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EnhancedLocation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RouteProgressEvent {
  RouteProgressEvent({
    required this.progress,
    required this.timestamp,
  });

  RouteProgress progress;

  int timestamp;

  List<Object?> _toList() {
    return <Object?>[
      progress,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RouteProgressEvent decode(Object result) {
    result as List<Object?>;
    return RouteProgressEvent(
      progress: result[0]! as RouteProgress,
      timestamp: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RouteProgressEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RerouteEvent {
  RerouteEvent({
    required this.reason,
    required this.state,
    this.newRoute,
  });

  String reason;

  RerouteState state;

  RouteAlternative? newRoute;

  List<Object?> _toList() {
    return <Object?>[
      reason,
      state,
      newRoute,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RerouteEvent decode(Object result) {
    result as List<Object?>;
    return RerouteEvent(
      reason: result[0]! as String,
      state: result[1]! as RerouteState,
      newRoute: result[2] as RouteAlternative?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RerouteEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class ArrivalEvent {
  ArrivalEvent({
    required this.finalDestination,
    this.waypointIndex,
  });

  bool finalDestination;

  int? waypointIndex;

  List<Object?> _toList() {
    return <Object?>[
      finalDestination,
      waypointIndex,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ArrivalEvent decode(Object result) {
    result as List<Object?>;
    return ArrivalEvent(
      finalDestination: result[0]! as bool,
      waypointIndex: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ArrivalEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class OffRouteEvent {
  OffRouteEvent({
    required this.distanceFromRoute,
    required this.timestamp,
  });

  double distanceFromRoute;

  int timestamp;

  List<Object?> _toList() {
    return <Object?>[
      distanceFromRoute,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static OffRouteEvent decode(Object result) {
    result as List<Object?>;
    return OffRouteEvent(
      distanceFromRoute: result[0]! as double,
      timestamp: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OffRouteEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class NavigationStateEvent {
  NavigationStateEvent({
    required this.state,
    required this.timestamp,
  });

  NavigationState state;

  int timestamp;

  List<Object?> _toList() {
    return <Object?>[
      state,
      timestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NavigationStateEvent decode(Object result) {
    result as List<Object?>;
    return NavigationStateEvent(
      state: result[0]! as NavigationState,
      timestamp: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _NavigationPigeonCodec extends StandardMessageCodec {
  const _NavigationPigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NavigationState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CameraMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is VoiceUnits) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is ManeuverType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is ManeuverModifier) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is RerouteState) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is RouteOptions) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is NavigationOptions) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is CameraPadding) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is RouteLineOptions) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is ManeuverArrowOptions) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is CameraAnimationOptions) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is LaneInfo) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is Lane) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is RouteProgress) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is RouteStep) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is BannerInstruction) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is VoiceInstruction) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is RouteAlternative) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is EnhancedLocation) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is RouteProgressEvent) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is RerouteEvent) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is ArrivalEvent) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is OffRouteEvent) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is NavigationStateEvent) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NavigationState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraMode.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : VoiceUnits.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ManeuverType.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : ManeuverModifier.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : RerouteState.values[value];
      case 135:
        return RouteOptions.decode(readValue(buffer)!);
      case 136:
        return NavigationOptions.decode(readValue(buffer)!);
      case 137:
        return CameraPadding.decode(readValue(buffer)!);
      case 138:
        return RouteLineOptions.decode(readValue(buffer)!);
      case 139:
        return ManeuverArrowOptions.decode(readValue(buffer)!);
      case 140:
        return CameraAnimationOptions.decode(readValue(buffer)!);
      case 141:
        return LaneInfo.decode(readValue(buffer)!);
      case 142:
        return Lane.decode(readValue(buffer)!);
      case 143:
        return RouteProgress.decode(readValue(buffer)!);
      case 144:
        return RouteStep.decode(readValue(buffer)!);
      case 145:
        return BannerInstruction.decode(readValue(buffer)!);
      case 146:
        return VoiceInstruction.decode(readValue(buffer)!);
      case 147:
        return RouteAlternative.decode(readValue(buffer)!);
      case 148:
        return EnhancedLocation.decode(readValue(buffer)!);
      case 149:
        return RouteProgressEvent.decode(readValue(buffer)!);
      case 150:
        return RerouteEvent.decode(readValue(buffer)!);
      case 151:
        return ArrivalEvent.decode(readValue(buffer)!);
      case 152:
        return OffRouteEvent.decode(readValue(buffer)!);
      case 153:
        return NavigationStateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NavigationInterface {
  /// Constructor for [NavigationInterface].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NavigationInterface(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec =
      _NavigationPigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Start a navigation session with options
  Future<bool> startNavigation(NavigationOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.startNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Stop the current navigation session
  Future<bool> stopNavigation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.stopNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Pause navigation (keep session alive but stop guidance)
  Future<bool> pauseNavigation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.pauseNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Resume paused navigation
  Future<bool> resumeNavigation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.resumeNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Get current navigation state
  Future<NavigationState> getNavigationState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getNavigationState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NavigationState?)!;
    }
  }

  /// Request and set a route
  Future<bool> setRoute(RouteOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Clear current route
  Future<bool> clearRoute() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.clearRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Request route alternatives
  Future<List<RouteAlternative>> getRouteAlternatives() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getRouteAlternatives$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!
          .cast<RouteAlternative>();
    }
  }

  /// Select an alternative route by ID
  Future<bool> selectAlternativeRoute(String routeId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.selectAlternativeRoute$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[routeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Get current route progress (returns null if no active route)
  Future<RouteProgress?> getCurrentProgress() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getCurrentProgress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RouteProgress?);
    }
  }

  /// Get current location with map matching
  Future<EnhancedLocation?> getCurrentLocation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getCurrentLocation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as EnhancedLocation?);
    }
  }

  /// Set camera mode
  Future<void> setCameraMode(CameraMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setCameraMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[mode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get current camera mode
  Future<CameraMode> getCameraMode() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getCameraMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CameraMode?)!;
    }
  }

  /// Update camera padding
  Future<void> setCameraPadding(CameraPadding padding) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setCameraPadding$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[padding]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Mute or unmute voice instructions
  Future<void> setVoiceMuted(bool muted) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setVoiceMuted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[muted]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Check if voice is muted
  Future<bool> isVoiceMuted() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.isVoiceMuted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Set voice language (e.g., "en", "es", "pt")
  Future<void> setVoiceLanguage(String languageCode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setVoiceLanguage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[languageCode]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set voice units
  Future<void> setVoiceUnits(VoiceUnits units) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setVoiceUnits$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[units]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register for route progress events
  Future<void> registerProgressObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerProgressObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister from route progress events
  Future<void> unregisterProgressObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterProgressObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register for banner instruction events
  Future<void> registerBannerObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerBannerObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister from banner instruction events
  Future<void> unregisterBannerObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterBannerObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register for voice instruction events
  Future<void> registerVoiceObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerVoiceObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister from voice instruction events
  Future<void> unregisterVoiceObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterVoiceObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register for reroute events
  Future<void> registerRerouteObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerRerouteObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister from reroute events
  Future<void> unregisterRerouteObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterRerouteObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register for arrival events
  Future<void> registerArrivalObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerArrivalObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister from arrival events
  Future<void> unregisterArrivalObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterArrivalObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register for off-route events
  Future<void> registerOffRouteObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.registerOffRouteObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister from off-route events
  Future<void> unregisterOffRouteObserver() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.unregisterOffRouteObserver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set route line styling options
  Future<void> setRouteLineOptions(RouteLineOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setRouteLineOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get current route line options
  Future<RouteLineOptions> getRouteLineOptions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getRouteLineOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RouteLineOptions?)!;
    }
  }

  /// Set maneuver arrow styling options
  Future<void> setManeuverArrowOptions(ManeuverArrowOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setManeuverArrowOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get current maneuver arrow options
  Future<ManeuverArrowOptions> getManeuverArrowOptions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.getManeuverArrowOptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ManeuverArrowOptions?)!;
    }
  }

  /// Set camera mode with animation
  Future<void> setCameraModeAnimated(
      CameraMode mode, CameraAnimationOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.mapbox_maps_flutter.NavigationInterface.setCameraModeAnimated$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[mode, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class NavigationEventListener {
  static const MessageCodec<Object?> pigeonChannelCodec =
      _NavigationPigeonCodec();

  /// Called when route progress updates
  void onRouteProgress(RouteProgressEvent event);

  /// Called when banner instruction should be displayed
  void onBannerInstruction(BannerInstruction instruction);

  /// Called when voice instruction should be spoken
  void onVoiceInstruction(VoiceInstruction instruction);

  /// Called during reroute process
  void onReroute(RerouteEvent event);

  /// Called when arriving at waypoint or destination
  void onArrival(ArrivalEvent event);

  /// Called when driver goes off route
  void onOffRoute(OffRouteEvent event);

  /// Called when navigation state changes
  void onNavigationStateChanged(NavigationStateEvent event);

  static void setUp(
    NavigationEventListener? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onRouteProgress$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onRouteProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RouteProgressEvent? arg_event =
              (args[0] as RouteProgressEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onRouteProgress was null, expected non-null RouteProgressEvent.');
          try {
            api.onRouteProgress(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onBannerInstruction$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onBannerInstruction was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BannerInstruction? arg_instruction =
              (args[0] as BannerInstruction?);
          assert(arg_instruction != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onBannerInstruction was null, expected non-null BannerInstruction.');
          try {
            api.onBannerInstruction(arg_instruction!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onVoiceInstruction$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onVoiceInstruction was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VoiceInstruction? arg_instruction =
              (args[0] as VoiceInstruction?);
          assert(arg_instruction != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onVoiceInstruction was null, expected non-null VoiceInstruction.');
          try {
            api.onVoiceInstruction(arg_instruction!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onReroute$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onReroute was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RerouteEvent? arg_event = (args[0] as RerouteEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onReroute was null, expected non-null RerouteEvent.');
          try {
            api.onReroute(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onArrival$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onArrival was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ArrivalEvent? arg_event = (args[0] as ArrivalEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onArrival was null, expected non-null ArrivalEvent.');
          try {
            api.onArrival(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onOffRoute$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onOffRoute was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final OffRouteEvent? arg_event = (args[0] as OffRouteEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onOffRoute was null, expected non-null OffRouteEvent.');
          try {
            api.onOffRoute(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onNavigationStateChanged$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onNavigationStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final NavigationStateEvent? arg_event =
              (args[0] as NavigationStateEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.mapbox_maps_flutter.NavigationEventListener.onNavigationStateChanged was null, expected non-null NavigationStateEvent.');
          try {
            api.onNavigationStateChanged(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
